global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'agentservice'
    static_configs:
      - targets: ['agentservice:8000']          # container name, resolved by Docker network

  - job_name: 'transformers_service'
    static_configs:
      - targets: ['transformers_service:8000']

  - job_name: 'tfidf_svc'
    static_configs:
      - targets: ['tfidf_svc:8000']