# .github/workflows/ci-tfidf.yml
name: CI â€“ TF-IDF Service
on:
  push:
    paths:
      - 'src/services/tfidf_service/app.py'
      - 'src/models/mlflow_tfidf.py'
      - '.github/workflows/lint-test.yml'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/lint-test.yml
    with:
      service-path: src/services/tfidf_service
      service-name: app
      needs-real-model: true

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      service-name: tfidf
      dockerfile: docker/tfidf_svc.Dockerfile